package es.justWeddings.domain;

// Generated 08-Nov-2016 20:05:02 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "guest")
public class Guest implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", referencedColumnName = "ID", nullable = false)
	private User user;
	@Column(name="NAME")
	private String name;
	@Column(name="LAST_NAME")
	private String lastName;
	@Column(name="SEX")
	private String sex;
	@Column(name="ALLERGE")
	private String allerge;
	@Column(name="GUESTS_GROUP")
	private String group;
	@Column(name="VEGETARIAN")
	private String vegetarian;
	@Column(name="BUS_REQUIRED")
	private String busRequired;
	@Column(name="CONFIRMATION_RECEIVED")
	private String confirmationReceived;
	@Column(name="INVITATION_SEND")
	private String invitationSend;
	@Column(name="INVITED_BY")
	private String invitedBy;
	@OneToMany(mappedBy="id")
	private Set<Guest> guests = new HashSet<Guest>(0);

	public Guest() {
	}

	public Guest(Guest guest, String name, String lastName, String sex) {
		this.name = name;
		this.lastName = lastName;
		this.sex = sex;
	}

	public Guest(Guest guest, User user, String name, String lastName,
			String sex, String allerge, String vegetarian, String isUserFriend,
			Set<Guest> guests) {
		this.user = user;
		this.name = name;
		this.lastName = lastName;
		this.sex = sex;
		this.allerge = allerge;
		this.vegetarian = vegetarian;
		this.invitedBy = isUserFriend;
		this.guests = guests;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAllerge() {
		return allerge;
	}

	public void setAllerge(String allerge) {
		this.allerge = allerge;
	}

	public String getGroup() {
		return group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	public String getVegetarian() {
		return vegetarian;
	}

	public void setVegetarian(String vegetarian) {
		this.vegetarian = vegetarian;
	}

	public String getBusRequired() {
		return busRequired;
	}

	public void setBusRequired(String busRequired) {
		this.busRequired = busRequired;
	}

	public String getConfirmationReceived() {
		return confirmationReceived;
	}

	public void setConfirmationReceived(String confirmationReceived) {
		this.confirmationReceived = confirmationReceived;
	}

	public String getInvitationSend() {
		return invitationSend;
	}

	public void setInvitationSend(String invitationSend) {
		this.invitationSend = invitationSend;
	}

	public String getInvitedBy() {
		return invitedBy;
	}

	public void setInvitedBy(String invitedBy) {
		this.invitedBy = invitedBy;
	}

	public Set<Guest> getGuests() {
		return guests;
	}

	public void setGuests(Set<Guest> guests) {
		this.guests = guests;
	}


}