package es.justWeddings.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "outlays")
public class Outlays implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="NAME")
	private String name;
	@OneToMany(mappedBy="outlay")
	private Set<Outlays4wedding> outlays4wedding = new HashSet<Outlays4wedding>();

	public Outlays() {
	}

	public Outlays(String name) {
		this.name = name;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Outlays4wedding> getSupplier4wedding() {
		return outlays4wedding;
	}

	public void setSupplier4wedding(Set<Outlays4wedding> supplier4wedding) {
		this.outlays4wedding = supplier4wedding;
	}

	@Override
	public String toString() {
		return name;
	}

}