package es.justWeddings.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "suppliers4wedding")
public class Suppliers4wedding implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="NAME")
	private String name;
	@Column(name="CONFIRMED")
	private String confirmed;
	@Column(name="NOTES")
	private String notes;
	@Column(name="AMOUNT_PAID")
	private Double amountPaid;
	@Column(name="FINAL_PRICE")
	private Double finalPrice;
	@Column(name="ESTIMATED_PRICE")
	private Double estimatedPrice;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WEDDING_ID", referencedColumnName = "ID", nullable = false)
	private Wedding wedding;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPPLIER_ID", referencedColumnName = "ID", nullable = false)
	private Suppliers supplier;

	public Suppliers4wedding() {
	}

	public Suppliers4wedding(String name, Suppliers supplier, Wedding wedding) {
		this.name = name;
		this.supplier = supplier;
		this.wedding = wedding;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getConfirmed() {
		return confirmed;
	}

	public void setConfirmed(String confirmed) {
		this.confirmed = confirmed;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Double getAmountPaid() {
		return amountPaid;
	}

	public void setAmountPaid(Double amountPaid) {
		this.amountPaid = amountPaid;
	}

	public Double getFinalPrice() {
		return finalPrice;
	}

	public void setFinalPrice(Double finalPrice) {
		this.finalPrice = finalPrice;
	}

	public Double getEstimatedPrice() {
		return estimatedPrice;
	}

	public void setEstimatedPrice(Double stimatedPrice) {
		this.estimatedPrice = stimatedPrice;
	}

	public Wedding getWedding() {
		return wedding;
	}

	public void setWedding(Wedding wedding) {
		this.wedding = wedding;
	}

	public Suppliers getSupplier() {
		return supplier;
	}

	public void setSupplier(Suppliers supplier) {
		this.supplier = supplier;
	}
	
	@Override
	public String toString() {
		return name;
	}

}