package es.justWeddings.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "suppliers")
public class Suppliers implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="NAME")
	private String name;
	@OneToMany(mappedBy="supplier")
	private Set<Suppliers4wedding> supplier4wedding = new HashSet<Suppliers4wedding>();

	public Suppliers() {
	}

	public Suppliers(String name) {
		this.name = name;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Suppliers4wedding> getSupplier4wedding() {
		return supplier4wedding;
	}

	public void setSupplier4wedding(Set<Suppliers4wedding> supplier4wedding) {
		this.supplier4wedding = supplier4wedding;
	}

	@Override
	public String toString() {
		return name;
	}

}