package es.justWeddings.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import es.justWeddings.domain.types.TableTypes;

/**
 * Guest generated by hbm2java
 */
@Entity
@Table(name = "tables")
public class Tables implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name="NAME")
	private String name;
	@Column(name="TYPE")
	private String type;
	@Column(name="NUMBER")
	private Integer number;
	@Column(name="INVITED_BY")
	private String invitedBy;
	@Column(name="X_POSITION")
	private Integer xPosition;
	@Column(name="Y_POSITION")
	private Integer yPosition;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "WEDDING_ID", referencedColumnName = "ID", nullable = false)
	private Wedding wedding = new Wedding();

	public Tables() {
	}

	public Tables(String name, String type, String invitedBy,Integer number) {
		this.name = name;
		this.type = type;
		this.invitedBy = invitedBy;
		this.number = number;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return type;
	}
	public String getTypeName() {
		return TableTypes.valueOf(type).name();
	}

	public void setLastName(String type) {
		this.type = type;
	}

	public Integer getNumber() {
		return number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getInvitedBy() {
		return invitedBy;
	}

	public void setInvitedBy(String invitedBy) {
		this.invitedBy = invitedBy;
	}

	public Integer getxPosition() {
		return xPosition;
	}

	public void setxPosition(Integer xPosition) {
		this.xPosition = xPosition;
	}

	public Integer getyPosition() {
		return yPosition;
	}

	public void setyPosition(Integer yPosition) {
		this.yPosition = yPosition;
	}

	public void setType(String type) {
		this.type = type;
	}
}